"""Application configuration loaded from environment / .env.

Two independent axes control how the demo runs:

* **Data systems (Databricks + D365)** are *always mocked* in this demo. They
  read the deterministic JSON data pack under ``data/`` so the flow is
  reproducible without any external system. (`mock_mode`, default ``True``.)
* **Foundry reasoning** can run in one of two modes (`foundry_mode`):
    - ``mock`` (default): the recommendation narration is generated locally by a
      deterministic template — no Azure calls, fully offline.
    - ``live``: the narration is generated by a real Azure AI Foundry model
      deployment. Decisions and guardrails stay deterministic in *both* modes;
      only the natural-language explanation changes.

This lets the React app offer two experiences: (1) entirely mock, and (2) real
Foundry reasoning with mock data / Databricks / D365.
"""

from __future__ import annotations

from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    # Data-system mode (Databricks + D365) — always mocked in this demo.
    mock_mode: bool = True
    cors_origins: str = "http://localhost:5173,http://localhost:4173"

    # Foundry reasoning mode — "mock" (offline) or "live" (real Azure model).
    foundry_mode: Literal["mock", "live"] = "mock"

    # When true (and foundry_mode resolves to live), live narration is produced
    # by a *persistent Foundry agent* (created in the project, visible in the
    # portal) instead of a raw chat completion. Falls back to chat completion,
    # then to the deterministic mock template, if the agent path is unavailable.
    foundry_use_agents: bool = False

    # Microsoft Foundry (Azure AI Foundry)
    azure_foundry_project_endpoint: str | None = None
    azure_foundry_model_deployment: str = "gpt-4o"
    azure_foundry_api_version: str = "2024-10-21"
    azure_tenant_id: str | None = None

    # Application Insights — when set, the backend exports OpenTelemetry GenAI
    # traces here so they appear in the Foundry portal Tracing / Monitoring tabs.
    # The same resource is wired to the project via a Foundry AppInsights
    # connection (see infra/bicep/main.bicep).
    applicationinsights_connection_string: str | None = None

    # Databricks (system of intelligence)
    databricks_host: str | None = None
    databricks_warehouse_id: str | None = None
    databricks_http_path: str | None = None
    databricks_token: str | None = None

    # D365 F&O (system of record) / MCP write path
    d365_base_url: str | None = None
    d365_mcp_endpoint: str | None = None
    d365_client_id: str | None = None
    d365_client_secret: str | None = None

    # Approval channel (Microsoft Teams)
    teams_approval_webhook: str | None = None

    @property
    def cors_origin_list(self) -> list[str]:
        return [o.strip() for o in self.cors_origins.split(",") if o.strip()]

    @property
    def foundry_live_available(self) -> bool:
        """Live Foundry reasoning requires a project endpoint to be configured."""
        return bool(self.azure_foundry_project_endpoint)

    @property
    def tracing_enabled(self) -> bool:
        """OpenTelemetry export to App Insights is on when a connection string is set."""
        return bool(self.applicationinsights_connection_string)

    def resolve_foundry_mode(self, requested: str | None = None) -> Literal["mock", "live"]:
        """Resolve the effective Foundry mode for a request.

        A request may override the configured default, but ``live`` is only
        honored when a project endpoint is configured.
        """
        mode = requested or self.foundry_mode
        if mode == "live" and self.foundry_live_available:
            return "live"
        return "mock"


settings = Settings()
